### ISSUE TITLE
[BPMApp] Writing invalid values return an alaram but sets a wrong RB field

### ISSUE THREAD

**Issue by lerwys** [lnls-dig/bpm-epics-ioc#24]
**Problem:** On invalid write alarms, we must not change the RB value to this wrong value, as this does not reflect the hardware or device status.

**Solution:** Read the hardware status on each write.

**Comment by lerwys** [comment]
This must be fixed for RFFEApp in Hardware. Until then, the issue will remain open

**Comment by ericonr** [comment]
We moved from RFFEApp to a StreamDevice based IOC. So we can close this issue.
