### ISSUE TITLE
[BPMApp] Acquisition freezes when running automated Octave test script

### ISSUE THREAD

**Issue by danielot** [lnls-dig/bpm-epics-ioc#28]
**Problem:** The Octave script performs the following operations:

caput to the following PVs and values:

ACQChannel-Sel = 0
ACQSamplesPre-SP 100000
ACQSamplesPost-SP= 0
ACQShots-SP = 1
ACQTriggerRep-Sel = 0
ACQTrigger-Sel = 0

Loop with caput on ACQTriggerEvent-Sel = 0 every 1 second

caget on amplitude statistics PVs:

...STATSSigma_RBV
...STATSMinValue_RBV
...STATSMaxValue_RBV
...STATSMeanValue_RBV

The first statistics read gives 0 result in some BPMs (sometimes all BPMs).

After some iterations (~3 times), the acquisition freezes (sate "Acquiring..."). To return to nomral state an "aborting acquisition" is required.

After aborting, the test performed by the Octave script runs successfully, resulting in no more acquisition problems.

**Comment by lerwys** [comment]
The scripts starts all BPMs in a single "caput". So this is probably be related to the "shared" nature of HALCS for adjacent BPMs

**Comment by lerwys** [comment]
This is related to the maximum DDR3 memory bandwidth of 6400MB/s

Using the Sirius numbers (221MHz ADC clock), two adjacent BPMs "simultaneously" acquiring 100k samples gives us 221e6 (MHz) * 4 (bytes per data) * 4 (CH1/Ch2/Ch3/CH4) * 2 (BPMs) = 7072 MB/s

This is ~10% more than the theoretical bandwidth.

The approximately ADC frequency seems to be around 165 MHz. In this scenario, no stalls seem to happen. And 170 MHz stalls everytime.
