### ISSUE TITLE
[BPMApp] Use FFT plugin from area detector

### ISSUE THREAD

**Issue by lerwys** [lnls-dig/bpm-epics-ioc#40]
**Problem:** We are still using an old piece of code, called FFTRecord, that no one seems to be using or supporting it.

**Solution:** Use FFT plugin from AreaDetector module, that is used by other modules and much better supported. https://github.com/areaDetector/ADCore/blob/master/ADApp/pluginSrc/NDPluginFFT.cpp

**Comment by ericonr** [comment]
The AD plugin is limited to power-of-2 spans, and we don't want to depend on areadetector for new developments.
