### ISSUE TITLE
[Interlock] Improvements

### ISSUE THREAD

**Issue by lerwys** [lnls-dig/bpm-epics-ioc#54]
Suggestions from operations:

- [x] All "command" PVs should end with `-Cmd`, like: `IntlkClr-Sel` -> `IntlkClr-Cmd`
- [x] Check "masked" PVs. What is being masked
- [x] Check behavior of "clear" PVs. Need to go back to 0 after setting.
- [x] Change PV names from "Trans" to "Pos"
- [x] Change PV names from "bigger/smaller" to "upper/lower"

**Comment by danielot** [comment]
Should we close this issue?
