### ISSUE TITLE
[OPI] FFT graphs show strange spikes not present on raw data

### ISSUE THREAD

**Issue by lerwys** [lnls-dig/bpm-epics-ioc#7]
**Problem:** The FFT graphs show strange spikes on the spectrum. Processing the time-series data offline doe snot exhibit the problem.

**Comment by lerwys** [comment]
This can be reproduced with FMC250M passive boards and acquiring multiples of 72 points

**Comment by aylons** [comment]
This FFT is calculate in the CPU or in the FPGA?

**Comment by lerwys** [comment]
CPU. It's actually calculated by the RFFT Epics record located here: https://github.com/lnls-dig/bpm-epics-ioc/tree/master/FFTRecordsApp

**Comment by lerwys** [comment]
Not reproducible anymore
